{{- if .Values.priorityClass.create }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClass.name | default .Values.priorityClassName | default (include "gotenberg.fullname" .) }}
  labels:
    {{- include "gotenberg.labels" . | nindent 4 }}
value: {{ .Values.priorityClass.value }}
globalDefault: {{ .Values.priorityClass.globalDefault }}
description: {{ .Values.priorityClass.description | quote }}
{{- end }}
